# NumPy

NumPy is short for "Numerical Python". NumPy is a Python library used for working with arrays. It is a general purpose array-processing package.It provides a high performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

# Array
Array is an data structure that stores values of same data type. In, python, this is the main difference between with arrays and lists.While Python lists can obtain values corresponding to different data types, arrays in Python can only contain values corresponding to same data type.

In [2]:
# First we must import Numpy. NumPy is usually imported under the np alias.
import numpy as np

# Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray. We can create a NumPy ndarray object by using the array() function. To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [2]:
list_01=[1, 2, 3, 4, 5]
list_02= [6, 7, 8, 9, 10]
arr1=np.array(list_01)
arr2=np.array(list_02)

In [7]:
arr1

array([1, 2, 3, 4, 5])

In [41]:
type(arr1)

numpy.ndarray

In [4]:
#Checking NumPy Version
print(np.__version__)

1.21.5


# Dimension of Arrays:
A dimension in arrays is one level of array depth (nested arrays). 
Nested array: are arrays that have arrays as their elements.

# 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array. Example: Create a 0-D array with value 100 and check it's shape. Also check number of dimension of the array.

In [14]:
arr = np.array(100)
print(arr)
print(arr.shape)
print(arr.ndim)

100
()
0


# 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array. These are the most common and basic arrays. Example: Create a 1-D array containing the values 1,2,3,4,5 and check it's shape. Also check number of dimension of the array.

In [13]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
print(arr.ndim)

[1 2 3 4 5]
(5,)
1


# 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors. NumPy has a whole sub module dedicated towards matrix operations called numpy.mat. 2 Bracket means 2 dimensional array. Example: 

In [18]:
list_01=[1, 2, 3, 4, 5, 6]
list_02= [6, 7, 8, 9, 10, 11]

In [19]:
arr=np.array([list_01, list_02])

In [20]:
print(arr)
print(arr.ndim)

[[ 1  2  3  4  5  6]
 [ 6  7  8  9 10 11]]
2


# 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array. These are often used to represent a 3rd order tensor. Example: Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3,4,5 and 6,7,8,9,10. Also check number of dimension of the array.

In [21]:
arr=np.array([[[1,2,3,4,5], [6,7,8,9,10]],[[1,2,3,4,5], [6,7,8,9,10]]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
(2, 2, 5)
3


array.shape will also tell the number of Row and Colums.

Reshape can be done by array.reshape method. While doing so, number of elements in an array must be equal.

In [22]:
arr.shape

(2, 2, 5)

In [26]:
reshape_arr1=arr.reshape(10,2)
print(reshape_arr1)
print(reshape_arr1.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(10, 2)


In [23]:
reshape_arr2=arr.reshape(2,9)
print(reshape_arr2)
print(reshape_arr2.shape)

[[ 1  2  3  4  5  6  6  7  8]
 [ 9 10 11 11 12 13 14 15 16]]
(2, 9)


In [30]:
reshape_arr3=arr.reshape(2,10)
print(reshape_arr3)
print(reshape_arr3.shape)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
(2, 10)


In [28]:
reshape_arr4=arr.reshape(1,20)
print(reshape_arr4)
print(reshape_arr4.shape)

[[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10]]
(1, 20)


In [29]:
reshape_arr5=arr.reshape(20,1)
print(reshape_arr5)
print(reshape_arr5.shape)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
(20, 1)


# NumPy Array Indexing: Access Array Elements
Array indexing is the same as accessing an array element. One can access an array element by referring to its index number. The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc. We have 1D, 2D and 3D array for indexing learning purpose here.

In [50]:
list_01=[1, 2, 3, 4, 5, 6]
list_02= [6, 7, 8, 9, 10, 11]
list_03=[11, 12, 13, 14, 15, 16]
list_04= [16, 17, 18, 19, 20, 21]
arr_01D= np.array(list_01)
arr_02D=np.array([list_01, list_02])
arr_03D=np.array([[list_01, list_02], [list_03, list_04]])
print('The 1D array is:\n', arr_01D)
print('The 2D array is:\n', arr_02D)
print("The 3D array is:\n", arr_03D)

The 1D array is:
 [1 2 3 4 5 6]
The 2D array is:
 [[ 1  2  3  4  5  6]
 [ 6  7  8  9 10 11]]
The 3D array is:
 [[[ 1  2  3  4  5  6]
  [ 6  7  8  9 10 11]]

 [[11 12 13 14 15 16]
  [16 17 18 19 20 21]]]


# 1-D Array
01. Get the 3rd element from 1-D Array

# 2-D Array
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element. Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.
01. Access the element on the first row, second column.
02. Access the element on the 2nd row, 5th column.
# 3-D Array
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.
01. Access the third element of the second array of the first array.

In [61]:
print('3rd element of 1-D Array is:', arr_01D[2])
print('Element on the first row, second column of 2-D Array is:', arr_02D[0,1])
print('Element on the 2nd row, 5th column of 2-D Array is:', arr_02D[1,4])
print('3rd Element of the 2nd Array of the 1st Array is:', arr_03D[0,1,2])

3rd element of 1-D Array is: 3
Element on the first row, second column of 2-D Array is: 2
Element on the 2nd row, 5th column of 2-D Array is: 10
3rd Element of the 2nd Array of the 1st Array is: 8


In [9]:
arr01=np.array([[1,2,3],
              [4,5,6],
              [6,7,8]])
arr02=np.array([1,2,3])
print(arr01)
print(arr02)
print(arr01.shape)
print(arr02.shape)
print(arr01@arr02)

[[1 2 3]
 [4 5 6]
 [6 7 8]]
[1 2 3]
(3, 3)
(3,)
[14 32 44]


In [16]:
b=np.ones((3,1))
c=b.T
print(b)
print(c)
print(b.shape)
print(c.shape)

[[1.]
 [1.]
 [1.]]
[[1. 1. 1.]]
(3, 1)
(1, 3)
